#!/bin/bash
# AgenticIoT — First Boot Setup
#
# This script runs ONCE automatically on the Pi's first boot.
# It is generated by scripts/New-PiBootConfig.ps1 on the dev machine
# and placed in the SD card's boot partition before the Pi is powered on.
#
# Placement (done automatically by New-PiBootConfig.ps1):
#   Pi OS Bookworm+  →  /boot/firmware/firstrun.sh
#   Pi OS Bullseye   →  /boot/firstrun.sh
#
# DO NOT run this script manually.

set +e
exec > /var/log/iot-firstrun.log 2>&1

echo "[$(date)] AgenticIoT first-boot setup starting..."

# ─── Locate boot partition ────────────────────────────────────────────────────
BOOT_CREDS=""
for candidate in \
    "/boot/firmware/iot-credentials.env" \
    "/boot/iot-credentials.env"; do
    if [ -f "$candidate" ]; then
        BOOT_CREDS="$candidate"
        break
    fi
done

if [ -z "$BOOT_CREDS" ]; then
    echo "[$(date)] ERROR: iot-credentials.env not found on boot partition — skipping IoT setup"
    exit 0
fi

echo "[$(date)] Found credentials at $BOOT_CREDS"

# ─── Source credentials ───────────────────────────────────────────────────────
# shellcheck source=/dev/null
set -a
source "$BOOT_CREDS"
set +a

if [ -z "$DPS_ID_SCOPE" ]; then
    echo "[$(date)] ERROR: DPS_ID_SCOPE is empty — skipping IoT setup"
    exit 0
fi

if [ -z "$DPS_GROUP_KEY" ]; then
    echo "[$(date)] ERROR: DPS_GROUP_KEY is empty — skipping IoT setup"
    exit 0
fi

# ─── Wait for network ─────────────────────────────────────────────────────────
echo "[$(date)] Waiting for network connectivity..."
for i in $(seq 1 30); do
    if curl -s --max-time 5 https://github.com > /dev/null 2>&1; then
        echo "[$(date)] Network ready (attempt $i)"
        break
    fi
    echo "[$(date)] Waiting... attempt $i/30"
    sleep 5
done

# ─── Run unattended bootstrap ─────────────────────────────────────────────────
echo "[$(date)] Downloading and running unattended bootstrap..."

export DPS_ID_SCOPE
export DPS_GROUP_KEY
export DEVICE_ID

curl -sSL \
    https://raw.githubusercontent.com/Andworx/copilot-iot-service/main/raspberry-pi/bootstrap-unattended.sh \
    | bash

BOOTSTRAP_EXIT=$?
echo "[$(date)] Bootstrap exited with code $BOOTSTRAP_EXIT"

# ─── Securely delete credentials from boot partition ─────────────────────────
echo "[$(date)] Removing credentials from boot partition..."
shred -u "$BOOT_CREDS" 2>/dev/null || rm -f "$BOOT_CREDS"
echo "[$(date)] Credentials removed from boot partition"

# ─── Mark first-run complete ──────────────────────────────────────────────────
echo "[$(date)] First-run complete. Rebooting in 10 seconds..."
sleep 10
reboot
